Medicine/Controllers/PatiantController.cs
using Medicine.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Medicine.Controllers
{
    public class PatiantController : Controller
    {
        
        // GET: Patiant
        public ActionResult AllPatiant()
        {
            Session["statusShow"] = false;
            return View(ModelDB.GetDB().Burdeneds.ToList());
           
        }
        public ActionResult PatiantDetailes(string id)
        {
            //if(ViewBag.searcDate!=null)
            //{
            //    Session["searcDate"] = ViewBag.searcDate;
            //}
            var patient = ModelDB.GetDB().Burdeneds.Single(b => b.Id == id);
            Session["Burdened"] = patient;
            Session["IdBurdened"] = id;
            return View(patient);
        }
        [HttpPost]
        public ActionResult PatiantDetailes(string id, string searchDate)
        {
            Session["searcDate"] = searchDate;
            Session["statusShow"] = true;
            //if (ViewBag.searcDate != null)
            //{
            //    Session["searcDate"] = ViewBag.searcDate;
            //}
            var patient = ModelDB.GetDB().Burdeneds.Single(b => b.Id == id);
            Session["Burdened"] = patient;
            Session["IdBurdened"] = id;
            return View(patient);
        }
        //פונקציה שמציגה את המיטה הנוכחית ותאריך השיבוץ
        public ActionResult PatiantMoveBed(string id)
        {
            //שמירת ת"ז המטופל
            var patient = ModelDB.GetDB().Burdeneds.Single(b => b.Id == id);
            Session["Burdened"] = patient;
            Session["IdBurdened"] = id;
            //שמירת נתוני המחלקה ברשימה
            var d = new SelectList(ModelDB.GetDB().Departments, "CodeDepartment", "DepartmentName");
            ViewBag.departments = d;
            //שמירת נתוני החדר ברשימה
            var r = new SelectList(ModelDB.GetDB().Rooms, "CodeRoom", "CodeRoom");
            ViewBag.rooms = r;
            //שליפת האשפוז הנוכחי של הטופל הספציפי
            Hospitalizations h = ModelDB.GetDB().Hospitalizations.Where(a => a.IdBurdened == id &&
            a.ExitDate == null).FirstOrDefault();
            //שמירה במשתנה רשימה מסוג מיטות לאשפוז
            var beds = new List<HospitalizationBeds>();
            //בדיקה האם המטופל אכן מאושפז
            if (h != null)
            {
                beds = h.HospitalizationBeds.Where(bed => bed.EndDate != null).ToList();
                //שליפת המיטה הנוכחית
                HospitalizationBeds current = h.HospitalizationBeds.Where(bed => bed.EndDate != null).FirstOrDefault();
                if (current != null)
                {
                    //שמירה ב viewBag
                    ViewBag.currentBed = "מספר מיטה " + current.CodeBed + " . תאריך שיבוץ : " + current.BeginDate;
                }
            }
            return View("Bed", beds);
            //ViewBag.message = "מטופל אינו משובץ במיטה";
            //return PartialView("Messege");
        }
        //string BurdenedId = ((Burdeneds)Session["Burdened"]).Id;
        //    return View(aa.Burdeneds.Single(b => b.Id == BurdenedId).Hospitalizations);

        //     string WorkerId = Session["Id"].ToString();
        //Workers worker = ModelDB.GetDB().Workers.Single(w => w.Id == WorkerId);
        //    return View(worker);
        public PartialViewResult Bed()
        {
            var d = new SelectList(ModelDB.GetDB().Departments, "CodeDepartment", "DepartmentName");
            ViewBag.departments = d;
            var r = new SelectList(ModelDB.GetDB().Rooms, "CodeRoom", "CodeRoom");
            ViewBag.rooms = r;
            string BurdenedId = Session["IdBurdened"].ToString();
            Hospitalizations h = ModelDB.GetDB().Hospitalizations.Where(a => a.IdBurdened == BurdenedId && a.ExitDate == null).FirstOrDefault();
            var beds = new List<HospitalizationBeds>();
            if (h != null)
            {
                beds = h.HospitalizationBeds.Where(bed => bed.EndDate != null).ToList();
                HospitalizationBeds current = h.HospitalizationBeds.Where(bed => bed.EndDate != null).FirstOrDefault();
                if (current != null)
                {
                    ViewBag.currentBed = "מספר מיטה " + current.CodeBed + " . תאריך שיבוץ : " + current.BeginDate;
                }
            }
            return PartialView(beds);
        }
        //פונקציה לבחירת חדר המחזירה את חדרי המחלקה
        [HttpGet]
        public ActionResult GetRooms(int departmentId)
        {
            //שליפת החדרים הפעילים בתוך המחלקה הספציפית והכנסתם לרשימה
            var rooms = ModelDB.GetDB().Departments.Single(d => d.CodeDepartment == departmentId).Rooms
                .Where(r => r.Active == true).Select(r => new { Text = r.CodeRoom, Value = r.CodeRoom });
            //foreach (var item in rooms)
            //{
            //    ModelDB.GetDB().HospitalizationBeds.Where(x=>x.CodeRoom == item.Value && x.e)
            //}
            return Json(rooms, JsonRequestBehavior.AllowGet);
        }
        //פונקציה לבחירת מיטה המחזירה רק את המיטות הפעילות
        [HttpGet]
        public ActionResult GetBeds(int roomId)
        {
            //רשימת כל המיטות בחדר המבוקש שפעילות
            List<Beds> beds = ModelDB.GetDB().Rooms.Single(r => r.CodeRoom == roomId).Beds.Where(b => b.Active == true).ToList();
            List<Beds> s = new List<Beds>();
            foreach (var item in beds)
            {               
                //שליפת כל המיטות לאישפוז המתאימות שכרגע לא מאושפזים בהם
                HospitalizationBeds m = ModelDB.GetDB().HospitalizationBeds
                    .Where(x => x.CodeBed == item.CodeBed && x.EndDate != null).FirstOrDefault();
                if (m != null)//אם קיים כאלה
                {
                    //Beds current = ModelDB.GetDB().Beds.Where(x => x.CodeBed == m.CodeBed).FirstOrDefault();
                    s.Add(item);
                }
                else
                {
                    //שליפת המיטות שעדיין אף פעם לא התאשפזו בהם
                    HospitalizationBeds k = ModelDB.GetDB().HospitalizationBeds.Where(x => x.CodeBed == item.CodeBed).FirstOrDefault();
                    if (k == null)//אם קיים כאלה
                        s.Add(item);//תוסיף אותם לרשימת המיטות לאישפוז
                }

            }
            var beds2 = s.Select(b => new { Text = b.CodeBed, Value = b.CodeBed });
            return Json(beds2, JsonRequestBehavior.AllowGet);
        }
        public PartialViewResult Medicines()
        {
            List<HospitalizationMedicine> medicines = new List<HospitalizationMedicine>();
            string BurdenedId = ((Burdeneds)Session["Burdened"]).Id;
            //aa.Burdeneds.Single(b => b.Id == BurdenedId).Hospitalizations.Where(h=>h.ExitDate==null);
            foreach (var item in ModelDB.GetDB().Burdeneds.Single(b => b.Id == BurdenedId).Hospitalizations.Where(h => h.ExitDate != null))
            {
                medicines.AddRange(item.HospitalizationMedicine);
            }
            return PartialView("Medicines", medicines);
        }
        //public ActionResult MedicinesDetailes()//פרטי תרופה
        //{
        //    string BurdenedId = ((Burdeneds)Session["Burdened"]).Id;
        //    return View(ModelDB.GetDB().Burdeneds.Single(b => b.Id == BurdenedId).HourForMedicine);
        //}
        public ActionResult Search(string searchDate, string id)
        {
            DateTime d = DateTime.Parse(searchDate);
            Hospitalizations hospitalInDates = ModelDB.GetDB().Hospitalizations.Where(x => x.IdBurdened == id && x.EnteringDate <=d && x.ExitDate >= d).FirstOrDefault();
            return RedirectToAction("OldHospitalization");
        }

        public ActionResult Demobilization()
        {
            return View();
        }
        public ActionResult NewPatiant()
        {
            return View();
        }
        [HttpPost]
        public ActionResult NewPatiant(Burdeneds burdend)
        {
            if (ModelState.IsValid)
            {
                //בדיקת תקינות
                ViewBag.patiantIsExist = "";
                Burdeneds b = ModelDB.GetDB().Burdeneds.Where(a => a.Id == burdend.Id).FirstOrDefault();
                if (b != null)
                {
                    ViewBag.patiantIsExist = "מטופל קיים במערכת";
                    return View("NewPatiant");
                }
                //ViewBag.contactNotExist = "";
                //Contact c = ModelDB.GetDB().Contact.Where(a => a.CodeContact == burdend.CodeContact).FirstOrDefault();
                //if (c == null)
                //{
                //    ViewBag.contactNotExist = "איש קשר אינו קיים";
                //    return View("NewPatiant");
                //}
                burdend.CodeContact = 1;
                ModelDB.GetDB().Burdeneds.Add(burdend);
                ModelDB.GetDB().SaveChanges();
                //עדכון בDB
                //להחזיר הודעה עודכן בהצלחה
                return View("AllPatiant");
            }
            else
                return View("NewPatiant");
        }

        //public ActionResult OldHospitalization()
        //{
        //    string PatiantId = Session["IdBurdened"].ToString();
        //    //Burdeneds patiant = ModelDB.GetDB().Burdeneds.Single(b => b.Id == PatiantId).Hospitalizations;
        //    List<Hospitalizations> f = ModelDB.GetDB().Hospitalizations.ToList();
        //    List<Hospitalizations> h = ModelDB.GetDB().Hospitalizations.Where(a => a.IdBurdened == PatiantId).ToList();
        //    return View(h);
        //}
        public PartialViewResult OldHospitalization()
        {

Medicine/Views/Shared/_DoctorLayout.cshtml

@{
    ViewBag.Title = "_DoctorLayout";
    Layout = "_Layout.cshtml";
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap.min.js"></script>
<h2 class="name">רופא</h2>

<div class="col-md-10">
    @RenderBody()
</div>

<div class="container">
    <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked" role="tablist">
            <li class="active">
                @Html.ActionLink("מטופלים", "AllPatiant", "Patiant")
            </li>
            @*<li class="disabled">
                @Html.ActionLink("פרטי מטופל", "", "")
                <ul class="nav nav-pills nav-stacked" role="tablist">
                    <li>@Html.ActionLink("אשפוזים קודמים", "OldHospitalization", "Patiant")</li>
                </ul>                
            </li>*@
        </ul>
    </div>
   
</div>

Medicine/Views/Shared/_HelpingPowerLayout.cshtml

@{
    ViewBag.Title = "_HelpingPowerLayout";
    Layout = "_Layout.cshtml";
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap.min.js"></script>
<h2 class="name">כח עזר</h2>

<div class="col-md-10">
    @RenderBody()
</div>

<div class="container">
<div class="col-md-2">
    <ul class="nav nav-pills nav-stacked" role="tablist">
        <li>@Html.ActionLink("לקיחת תרופה", "GivingMedicines", "Medicines")</li>
    </ul>
</div>

</div>

Medicine/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - PR System</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>

    <style>   
        .navbar-inverse{
            background-color:#2b491b !important;

        }
        body 
        {
            direction:rtl;
        }
        footer {
            height: 81px;
            bottom: 0px;
            font-family: Algerian;
            text-align: left;
        }
        #myNav {
            width: 100%;
            padding: 0px;
            position: relative;
        }
        #namelogin {
            position:absolute;
            right:0px;
        }

    </style>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
               <!--- <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>-->
             <!--@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })-->
            </div>
            <div class="navbar-collapse collapse">
                <ul id="myNav" class="nav navbar-nav">
                    <li>@Html.ActionLink("יציאה", "Login", "Worker")</li>
                    <li>@Html.ActionLink("עדכון פרטים", "Update", "Worker")</li>
                   <li id="namelogin" >                      
                        <p style="color:white">@Session["Name"]</p>
                    </li>
                </ul>
            </div>
        </div>
    </div>


    <div class="container body-content">
        @RenderBody() 

        <footer>
            <p>www.DrugsGiving.org.il</p>
        </footer>
    </div>
   
</body>
</html>

Medicine/Views/Shared/_ManagerLayout.cshtml

@{
    ViewBag.Title = "_ManagerLayout";
    Layout = "_Layout.cshtml";
}
<style>
    .flex-container {
        display: flex;
    }
    .name {
        color:pink;
    }
    /*.conBtn {
        width: 200px;
        background-color: aliceblue;
        position:absolute;
        left:0px;
    }*/
    .conAll {
        min-width: calc(100% - 300px);
        max-width: calc(100% - 300px);
        position: relative;
    }
    .mainCon {
        position: relative;
    }

       
</style>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap.min.js"></script>
<h2 class="name">מנהל</h2>



<div class="container mainCon row flex-container" style="direction:rtl">
    <div class="col conAll">
        @RenderBody()           
</div>
    <div class=" col conBtn ">
          <ul class="nav nav-pills nav-stacked" role="tablist">
                <li class="active">
                    <ul class="nav nav-pills nav-stacked" role="tablist">
                        <li>@Html.ActionLink("עובדים", "AllWorkers", "Worker")</li>
                    </ul>
                </li>
                <li class="active">
                    <ul class="nav nav-pills nav-stacked" role="tablist">
                        <li>@Html.ActionLink("מחלקות", "AllDepartments", "Department")</li>
                    </ul>
                </li>
                <li class="active">
                    <ul class="nav nav-pills nav-stacked" role="tablist">
                        <li>@Html.ActionLink("תרופות", "AllMedicines", "Medicines")</li>
                    </ul>
                </li>
                <li class="active">
                    <ul class="nav nav-pills nav-stacked" role="tablist">
                        <li>@Html.ActionLink("מטופלים", "AllPatiant", "Patiant")</li>
                    </ul>
                </li>

            </ul>
        </div>




   
</div>


Medicine/Views/Shared/_NourseLayout.cshtml

@{
    ViewBag.Title = "_NourseLayout";
    Layout = "_Layout.cshtml";
}
<style>
    .flex-container {
        display: flex;
    }

    .name {
        color: pink;
    }

    .conBtn {
        width: 200px;
        background-color: aliceblue;
        position: absolute;
        left: 0px;
    }

    .conAll {
        min-width: calc(100% - 300px);
        max-width: calc(100% - 300px);
        position: relative;
    }

    .mainCon {
        position: relative;
    }
</style>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap.min.js"></script>
<h2 class="name">אחות</h2>



<div class="container mainCon row flex-container" style="direction:rtl">
    <div class="col conAll">
        @RenderBody()
    </div>
    <div class=" col conBtn ">
        <ul class="nav nav-pills nav-stacked" role="tablist">
            <li class="active">
                <ul class="nav nav-pills nav-stacked" role="tablist">
                    <li>@Html.ActionLink("קבלת חולים", "AllPatiant", "Patiant")</li>
                </ul>
            </li>
            <li class="active">
                <ul class="nav nav-pills nav-stacked" role="tablist">
                    <li>@Html.ActionLink("עדכון שחרור", "Demobilization", "Patiant")</li>
                </ul>
            </li>
        </ul>
    </div>





</div>
